name: file_mcp
description: A STDIO MCP server for locating files on the local filesystem.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  dart_mcp: ^0.5.2
  stream_channel: ^2.1.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
